services:
  crm-database:
    profiles: ["backend"]
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${CRM_DB_USERNAME:-postgres}
      - POSTGRES_DB=${CRM_DB_NAME:-crm_db}
      - POSTGRES_PASSWORD=${CRM_DB_PASSWORD}
    volumes:
      - crm_db_data:/var/lib/postgresql/data
    networks:
      - crm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  keycloak-db:
    profiles: ["backend"]
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME:-postgres}
      - POSTGRES_DB=${KEYCLOAK_DB_NAME:-keycloak}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  keycloak:
    profiles: ["backend"]
    # In production, you should build the image and push it to a registry.
    # Then use the `image` directive instead of `build`.
    image: ghcr.io/optimce/kc-groupid-mapper:main
    restart: unless-stopped
    command: ["start", "--import-realm", "--verbose", "--proxy-headers=xforwarded", "--http-relative-path=/keycloak"]
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/prod-config.json
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=${KC_DB_USERNAME:-postgres}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME:-localhost}
      - KC_HTTP_ENABLED=true  # Required for health endpoints
      - KC_HEALTH_ENABLED=true  # Explicitly enable health endpoints (if needed)
      - KC_METRICS_ENABLED=true  # Optional: Enable metrics if you want additional monitoring
    volumes:
      - ./keycloak/realm/prod-config.json:/opt/keycloak/data/import/prod-config.json
    networks:
      - keycloak
      - api-gateway
      - reverse-proxy
    depends_on: 
      keycloak-db:
        condition: service_healthy

  # Sidecar container to check Keycloak health before starting dependent services
  keycloak-healthcheck:
    image: alpine/curl
    profiles: ["backend"]
    command: ["tail", "-f", "/dev/null"]  # Sleep forever
    networks:
      - keycloak
    depends_on:
      - keycloak
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://keycloak:9000/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  openfiles:
    profiles: ["backend"]
    image: totalplatform/openfiles:latest
    restart: unless-stopped
    environment:
      - OPENFILES_PORT=${OPENFILES_PORT:-8001}
      - OPENFILES_DATA_PATH=${OPENFILES_DATA_PATH:-/var/lib/openfiles}
    volumes:
      - openfiles_data:/var/lib/openfiles
    networks:
      - openfiles

  jaeger:
    profiles: ["backend"]
    image: jaegertracing/jaeger:latest
    restart: unless-stopped
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - opentelemetry

  swagger-doc-gen:
    profiles: ["init"]
    # user: 0:0
    image: alpine/curl:latest
    command: ["-fL", "https://optimce.github.io/crm-backend/swagger.yml", "-o", "/data/swagger.yaml"]
    volumes:
      - ./krakend_config:/data:z
    restart: on-failure

  krakend-config:
    profiles: ["init"]
    image: ghcr.io/optimce/swagger2krakend:main
    volumes:
      - ./krakend_config:/etc/krakend
    environment:
      - SWAGGER_FILE=/etc/krakend/swagger.yaml
      - OUTPUT_FILE=/etc/krakend/krakend.json
      - KEYCLOAK_URL=http://keycloak:8080
      - REALM_NAME=optimce-realm
      - BACKEND_HOST=http://crm-backend:80
      - ISSUER=http://localhost/keycloak/realms/optimce-realm
    restart: on-failure
    depends_on:
      swagger-doc-gen:
        condition: service_completed_successfully

  krakend:
    profiles: ["backend"]
    image: krakend:latest
    volumes:
      - ./krakend_config:/etc/krakend
    networks:
      - api-gateway
      - reverse-proxy
    depends_on:
      crm-backend:
        condition: service_started
      keycloak:
        condition: service_started

  reverse-proxy:
    profiles: ["frontend"]
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - reverse-proxy

  crm-backend:
    profiles: ["backend"]
    image: ghcr.io/optimce/crm-backend:main
    command: npm start
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=80
      - MICROSERVICE_NAME=crm-backend
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-http://localhost}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=80
      - IAM_SERVICE_NAME=${IAM_SERVICE_NAME:-KEYCLOAK}
      - IAM_REALM=${IAM_REALM:-optimce-realm}
      - IAM_REALM_NAME=${IAM_REALM_NAME:-optimce-realm}
      - IAM_BASE_URL=${IAM_BASE_URL:-http://keycloak:8080}
      - IAM_CLIENT_ID=${IAM_CLIENT_ID:-optimce-backend}
      - IAM_GRANT_TYPE=${IAM_GRANT_TYPE:-client_credentials}
      - IAM_CLIENT_SECRET=${IAM_CLIENT_SECRET}
      - STORAGE_SERVICE_NAME=openfiles
      - STORAGE_TARGET=http://openfiles:8001
      - STORAGE_DB_NAME=crm_files
      - STORAGE_TOKEN=${STORAGE_TOKEN}
      - REMOTE_LOGGING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - DB_TYPE=postgres
      - DB_HOST=crm-database
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=crm_db
    networks:
      - api-gateway
      - crm
      - keycloak
      - openfiles
      - opentelemetry
    depends_on:
      crm-database:
        condition: service_healthy
      keycloak-healthcheck:
        condition: service_healthy
      openfiles:
        condition: service_started
      jaeger:
        condition: service_started

  crm-frontend-config:
    profiles : ["init"]
    image: ghcr.io/ourouk/alpine-envsubst:main
    env_file:
      - .env
    volumes:
      - ./crm-frontend-config:/config
    command: 
      - < /config/config.template.json > /config/config.json

  crm-frontend:
    profiles: ["frontend"]
    image: ghcr.io/optimce/crm-frontend:main
    volumes:
      - ./crm-frontend-config/config.json:/usr/share/nginx/html/assets/config/config.json
    networks:
      - reverse-proxy
    # depends_on:
    #   crm-frontend-config:
    #     condition: service_completed_successfully

volumes:
  crm_db_data:
  keycloak_db_data:
  openfiles_data:
  krakend_config:
  keycloak_data:

networks:
  reverse-proxy:
  api-gateway:
  crm:
  keycloak:
  openfiles:
  opentelemetry: