global:
  extra_config: /app/extra-config.json

services:
  root:
    swagger: /config/root.yaml
    host: crm-backend:80
  generation:
    swagger: /config/generation.json
    host: allocation-key-generation:8002
  simulation:
    swagger: /config/simulation.json
    host: simulation-key:8000
  news:
    swagger: /config/news-board.json
    host: news-board:8000
