-- ============================================================================
-- Local database schema (LOCAL_DATABASE_URL) — live-data service.
--
-- Single source of truth for the LOCAL (owned) database. The CRM core tables
-- (community, meter, meter_data, member, address, …) live in a separate
-- database and are NOT declared here; this service only reads them, as
-- live_data_svc, constrained by postgres/provision/30-crm-grants.sql.
-- Cross-DB references (ean, id_community) are plain columns, NEVER foreign
-- keys.
--
-- Mirrors shared/models/local_models.py.
--
-- NO GRANT STATEMENTS. provision.sh applies this file under `SET ROLE
-- live_data_svc`, so it must be ownership-neutral. Access is granted in
-- postgres/provision/{10-databases,20-schema-owner,30-crm-grants}.sql.
--
-- NO psql META-COMMANDS (\i, \set, …) and no bind parameters. tests/conftest.py
-- feeds this whole file to asyncpg's simple-query protocol, not to psql.
--
-- RE-RUNNABLE. `CREATE TABLE IF NOT EXISTS` NEVER ADDS A COLUMN, so an added
-- column also needs an idempotent `ALTER TABLE … ADD COLUMN IF NOT EXISTS`
-- beside its block — otherwise re-applying this file silently does nothing and
-- it surfaces at runtime as an UndefinedColumnError.
--
-- APPLIED ONCE, IN PRACTICE. provision.sh applies a schema only when the target
-- database has no relation of relkind 'r' or 'p' in schema public. A
-- partitioned parent is relkind 'p', so an existing database is correctly
-- detected as non-empty — which also means THIS FILE IS NEVER RE-APPLIED to a
-- live database. Partition rotation therefore cannot live here; it is a runtime
-- job (build step 8). What this file does is provision the first six months and
-- leave behind the function that the job will call.
--
-- SCOPE: all eleven build steps. The ten tables from plan §6.1 that this header
-- once listed as "deliberately absent" — rollup_device_hour/_day,
-- rollup_community_hour/_day, rollup_dirty, device_owner_window,
-- forecast_production, device_forecast_method, consent and consent_event — ARE
-- IN THIS FILE. They were held back until steps 7/8 so that step 8's design
-- decisions could not be frozen into a step where nothing could test them, and
-- they arrived through scripts/sql/migrations/0001_*.sql.
--
-- This file and the migrations carry the SAME statements, for a fresh database
-- and for a live one respectively. tests/test_schema_migration_parity.py
-- provisions one of each and compares normalised catalog snapshots, which is
-- what keeps them equal. `consent` and `consent_event` are still INERT: phase 2.
-- ============================================================================

-- ---- Shared utilities ------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS schema_version (
    version      INTEGER     PRIMARY KEY,
    description  TEXT        NOT NULL,
    applied_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Read back by api/health/routes.py and compared with shared.const.
-- LOCAL_SCHEMA_VERSION. That comparison is what stops /health/readiness going
-- green over an EMPTY database: 10-databases.sql creates live_data_local before
-- any schema is applied, so a `SELECT 1` probe succeeds against zero tables and
-- the compose healthcheck is satisfied by a service that cannot store anything.
INSERT INTO schema_version (version, description) VALUES
    (1, 'Live-data initial schema (build steps 1-5)')
ON CONFLICT DO NOTHING;


-- ============================================================================
-- DEVICE
--
-- A device is anything that publishes the protocol on its topics with its
-- credentials. The hardware behind it is interchangeable.
-- ============================================================================

CREATE TABLE IF NOT EXISTS device (
    -- Internal surrogate key. INTEGER, not UUID, deliberately: `measurement` is
    -- the largest table this service will own and its primary key leads on this
    -- column, so the width is paid once per row AND once per index entry. The
    -- worker has to load the device row for every message anyway (community,
    -- status, ceiling, capacity), so resolving public_id -> id costs nothing
    -- extra — and it makes plan §7.5's "write last_reject_reason only for a
    -- device row that actually loaded" structurally impossible to violate: you
    -- cannot name the integer without having loaded the row.
    id                     INTEGER      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- The protocol's `device_id`. This is what appears in the topic, what IS the
    -- MQTT username, and what the enrolment response returns. Generated by
    -- OptimCE at device creation and pinned as the broker client id, so it is
    -- externally visible and must never be reused.
    public_id              UUID         NOT NULL UNIQUE,

    id_community           INTEGER      NOT NULL,

    -- shared.const.DeviceType. Phase 1 enrols PRODUCTION only (plan deviation 6).
    type                   SMALLINT     NOT NULL,

    -- The meter this device reports for. A PLAIN COLUMN, never an FK: it lives
    -- in crm_db. Validated against the CRM at creation time, because nothing
    -- else ever will — a typo'd EAN otherwise produces a device that ingests
    -- happily and is attributed to nobody, discovered months later with real
    -- data already stored against it.
    --
    -- NEVER denormalise id_member here. Ownership is resolved per timestamp
    -- (plan deviation 3): meter_data is time-sliced and a meter can change
    -- holder mid-month. A cached owner is the meter-transfer privacy leak — the
    -- previous occupant's credential keeps publishing, attributed to them, about
    -- someone else's household.
    ean                    VARCHAR(64)  NOT NULL,

    name                   VARCHAR(128) NOT NULL,

    -- shared.const.DeviceStatus: 1 PENDING, 2 ACTIVE, 3 REVOKED.
    status                 SMALLINT     NOT NULL DEFAULT 1,

    -- protocol §3.4. A smart meter's P1 port sees only the exchange with the
    -- grid. On a PURE INJECTION site (nothing consumes behind the meter) the
    -- export IS the production. Otherwise production is invisible and
    -- production_wh must be null — and OptimCE's views must say "export", not
    -- "production". Fixed at creation because it is a property of the site.
    pure_injection         BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Snapshot of crm_db meter_data.total_generating_capacity, taken at device
    -- creation. NAMED WITH ITS UNIT ON PURPOSE (plan deviation 4): the CRM
    -- column is documented in all four locales as the maximum power in kVA that
    -- the installation can INJECT — the AC inverter/connection limit, not the DC
    -- panel peak. A PV array is routinely oversized against its inverter, so
    -- this is a CEILING to clip against, never a capacity to trust.
    -- NULL for a device whose meter declares none.
    capacity_kva           NUMERIC(12, 3),

    -- Per-interval energy ceiling, applied to import_wh + export_wh. NULL means
    -- use settings.INGEST_DEFAULT_MAX_WH_PER_INTERVAL.
    max_wh_per_interval    DOUBLE PRECISION,

    -- Read from EVERY status message, not only at enrolment (protocol §3.2), so
    -- that a field upgrade is visible. "Which devices are running the broken
    -- 0.3.0?" is a question that only gets asked at the worst possible moment.
    connector_name         VARCHAR(64),
    connector_version      VARCHAR(32),

    enrolled_at            TIMESTAMPTZ,
    revoked_at             TIMESTAMPTZ,

    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- One live device per meter per community. Partial, so a revoked device does not
-- block re-enrolling the same meter — which is the normal recovery path when a
-- password is lost (protocol §5.2: the password is shown once and is never
-- recoverable).
CREATE UNIQUE INDEX IF NOT EXISTS uq_device_community_ean_live
    ON device (id_community, ean)
    WHERE status <> 3;

CREATE INDEX IF NOT EXISTS ix_device_community ON device (id_community);

DROP TRIGGER IF EXISTS trg_device_updated_at ON device;
CREATE TRIGGER trg_device_updated_at BEFORE UPDATE ON device
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================================
-- ENROLMENT TOKEN
--
-- Single use, 72 hours, hashed at rest. plan §8.3.
-- ============================================================================

CREATE TABLE IF NOT EXISTS enrollment_token (
    id             INTEGER      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_device      INTEGER      NOT NULL REFERENCES device (id) ON DELETE CASCADE,
    id_community   INTEGER      NOT NULL,

    -- SHA-256 of the Crockford base32 token. The token itself is 128 bits of
    -- CSPRNG output, so there is nothing for a KDF to slow down — and a bcrypt
    -- hash would ALSO break this index, forcing a scan over every live token on
    -- a request the gateway cuts at 3000 ms. "Compared in constant time" (plan
    -- §8.3) is satisfied by construction here: the comparison is an index probe,
    -- not a byte loop.
    token_hash     CHAR(64)     NOT NULL UNIQUE,

    expires_at     TIMESTAMPTZ  NOT NULL,

    -- THE CLAIM LEASE, and why there are two columns rather than one.
    --
    -- plan §8.2: create the broker client FIRST, commit SECOND. Of the two
    -- possible half-failures only one is recoverable — an orphan dynsec client
    -- with no device row is swept up harmlessly, but a committed device holding
    -- a secret that authenticates nothing, with its one-time token already
    -- consumed, is a site visit to a box with no keyboard.
    --
    -- So the token is CLAIMED for a few seconds before the broker call and only
    -- marked consumed after both sides are done. A 504 in between leaves a claim
    -- that simply expires, rather than burning a credential the member never
    -- received.
    claimed_until  TIMESTAMPTZ,
    consumed_at    TIMESTAMPTZ,

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- At most one unconsumed token per device. Issuing a new one invalidates the old.
CREATE UNIQUE INDEX IF NOT EXISTS uq_enrollment_token_device_unconsumed
    ON enrollment_token (id_device)
    WHERE consumed_at IS NULL;


-- ============================================================================
-- MEASUREMENT — partitioned monthly on ts
--
-- The primary key (id_device, ts) CONTAINS the partition key, which is what
-- makes `ON CONFLICT (id_device, ts) DO UPDATE` legal on the partitioned parent
-- — and that upsert is the whole of protocol §4.3's idempotence. A connector
-- that is unsure whether a message arrived is supposed to re-send it.
-- ============================================================================

CREATE TABLE IF NOT EXISTS measurement (
    id_device      INTEGER          NOT NULL,
    -- END of the interval, always (protocol §3.1 rule 1).
    ts             TIMESTAMPTZ      NOT NULL,

    -- Denormalised so that with_community_scope() can filter this table without
    -- a join. The house helper hard-codes `model.id_community` behind a
    -- `type: ignore`, so a table that does not carry this exact column name
    -- cannot be scoped at all.
    id_community   INTEGER          NOT NULL,

    interval_s     INTEGER          NOT NULL,

    -- DOUBLE PRECISION, never REAL. SUM(real) returns real, so step 8's rollups
    -- would accumulate float32 error across thousands of values and every
    -- displayed total would be quietly slightly wrong — nothing errors, and it
    -- is unfixable without rewriting history.
    import_wh      DOUBLE PRECISION NOT NULL,
    export_wh      DOUBLE PRECISION NOT NULL,
    production_wh  DOUBLE PRECISION,

    received_at    TIMESTAMPTZ      NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id_device, ts)
) PARTITION BY RANGE (ts);

-- A DEFAULT partition exists so that a row outside every declared range is
-- STORED rather than raising (plan §6.2 rule 2) — the difference between a late
-- message kept and a late message lost.
--
-- Its cost is that a stopped create-ahead job is invisible at write time. Two
-- things pay it back: api/health/routes.py reports this table's row count and
-- fails readiness above zero, and step 8's job must DRAIN the default before
-- attaching a partition over a range it already holds rows in — `ATTACH
-- PARTITION` fails otherwise, at 00:00 UTC on the first of a month,
-- platform-wide.
--
-- It also means plan §7.5's "on a partition miss, repair in a new session and
-- retry once" is UNREACHABLE by construction. The branch is kept in the worker
-- only as defence in case someone drops this table.
CREATE TABLE IF NOT EXISTS measurement_default PARTITION OF measurement DEFAULT;

-- Community-scoped reads over a time window (build step 6). Leads with
-- id_community because every scoped query filters on it first.
CREATE INDEX IF NOT EXISTS ix_measurement_community_ts
    ON measurement (id_community, ts);


-- ---- The partition registry and the create-ahead function ------------------
--
-- plan §6.2 requires that "the same helper is used by the schema and by the
-- scheduler". That is only LITERALLY true if the helper is SQL. A Python helper
-- emitting DDL, mirrored by static FOR VALUES literals here, is two helpers —
-- and they disagree the first time one is edited, surfacing months later as a
-- failed ATTACH.
--
-- domain/partitions.py mirrors the naming and bounds for tests and for step 8's
-- retention job; tests/test_partitions.py pins the two together by reading
-- pg_get_expr(relpartbound) back out.

CREATE TABLE IF NOT EXISTS live_partitioned_table (
    table_name  VARCHAR(63) PRIMARY KEY,
    added_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Step 8 adds 'rollup_device_hour' here AND to domain/partitions.py's
-- PARTITIONED_TABLES. A job that names only `measurement` lets the rollups
-- freeze about four months in while ingestion goes on looking perfectly healthy.
INSERT INTO live_partitioned_table (table_name) VALUES ('measurement')
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION live_ensure_monthly_partitions(
    months_ahead INTEGER DEFAULT 6,
    months_back  INTEGER DEFAULT 2
)
RETURNS INTEGER AS $$
DECLARE
  tbl          RECORD;
  offset_m     INTEGER;
  lower_bound  TIMESTAMPTZ;
  upper_bound  TIMESTAMPTZ;
  child        TEXT;
  created      INTEGER := 0;
BEGIN
  FOR tbl IN SELECT table_name FROM live_partitioned_table LOOP
    FOR offset_m IN -months_back..months_ahead LOOP
      -- Anchored to UTC EXPLICITLY. date_trunc() on a timestamptz truncates in
      -- the SESSION's timezone, and provision.sh sets none — so without the
      -- round trip through UTC a boundary would land at 23:00 or 01:00 of the
      -- previous day whenever the session happened to be Europe/Brussels, and
      -- every partition in the database would be an hour wide of the Python
      -- helper that names it.
      lower_bound := (date_trunc('month', (now() AT TIME ZONE 'UTC'))
                      + make_interval(months => offset_m)) AT TIME ZONE 'UTC';
      upper_bound := (date_trunc('month', (now() AT TIME ZONE 'UTC'))
                      + make_interval(months => offset_m + 1)) AT TIME ZONE 'UTC';
      child := format('%s_%s', tbl.table_name, to_char(lower_bound AT TIME ZONE 'UTC', 'YYYY_MM'));

      -- IF NOT EXISTS makes the whole function idempotent, which is what lets it
      -- be called both from this file and from a daily tick.
      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
        child, tbl.table_name, lower_bound, upper_bound
      );
      created := created + 1;
    END LOOP;
  END LOOP;
  RETURN created;
END;
$$ LANGUAGE plpgsql;

-- Provision the current month and six ahead. `schema.sql` creates its OWN
-- partitions (plan §6.2 rule 1) rather than leaving it to a running worker: a
-- test database provisioned from this file must be able to insert a row, and if
-- partitions arrived only from a worker, every test would be blocked on fixture
-- DDL executed inside a rolled-back transaction — which fails intermittently and
-- in test-order-dependent ways.
SELECT live_ensure_monthly_partitions(6, 2);


-- ============================================================================
-- DEVICE_LAST — one row per device, upserted
--
-- TWO CLOCKS, and they are not interchangeable.
--
--   ts          — the DEVICE's measurement clock. Guards the measurement
--                 columns: `WHERE ts < EXCLUDED.ts`, so a six-hour-old reading
--                 arriving in a backlog is not displayed as the current value
--                 with a fresh timestamp. That is the highest-visibility silent
--                 bug available here (plan §7.5).
--
--   status_at   — the SERVER's receipt clock. Guards the liveness and diagnostic
--                 columns. An LWT payload is composed at CONNECT time and sits
--                 on the broker until the device dies, so its `ts` is OLDER than
--                 every online status that followed it. Guarding `online` on the
--                 device clock makes the LWT lose the comparison and a crashed
--                 device shows online for ever — in a row that looks perfectly
--                 fresh. Receipt-time ordering also makes retained-status replay
--                 on resubscribe correct rather than harmful.
-- ============================================================================

CREATE TABLE IF NOT EXISTS device_last (
    id_device           INTEGER          PRIMARY KEY
                                         REFERENCES device (id) ON DELETE CASCADE,
    id_community        INTEGER          NOT NULL,

    -- Measurement clock.
    ts                  TIMESTAMPTZ,
    power_w             INTEGER,

    -- Server receipt clock.
    status_at           TIMESTAMPTZ,
    online              BOOLEAN,
    diag                VARCHAR(32),
    diag_since          TIMESTAMPTZ,

    -- Written ONLY for a device row that actually loaded. Writing it for an
    -- unknown device id would raise a foreign-key violation that aborts the
    -- whole ingest transaction — which is why device_unknown is message-scoped
    -- and never reaches here.
    last_reject_reason  VARCHAR(48),
    last_reject_at      TIMESTAMPTZ,

    -- Advanced by telemetry AND by status, so that "never seen" and "offline"
    -- are distinguishable inside the first quarter-hour after a connect.
    last_seen_at        TIMESTAMPTZ,

    updated_at          TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_device_last_community ON device_last (id_community);

DROP TRIGGER IF EXISTS trg_device_last_updated_at ON device_last;
CREATE TRIGGER trg_device_last_updated_at BEFORE UPDATE ON device_last
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================================
-- COMMUNITY_LIVE_SETTINGS
--
-- Created now, with plan §9.4's defaults, even though nothing reads it before
-- build step 6. The reason is narrow: the defaults are a PRIVACY decision, and
-- writing them down here means step 6 inherits them rather than inventing them
-- at the moment it needs a value.
--
-- members_see_aggregate = TRUE was justified in §9.4 by "otherwise every
-- member's signal screen is a 403 wall on day one". D-5 held the member screen,
-- so that justification is now vacuous — the DEFAULT may still be right, but the
-- reasoning must be re-made at step 6 rather than inherited. Recorded in
-- live-data-decisions.md rather than silently kept.
-- ============================================================================

CREATE TABLE IF NOT EXISTS community_live_settings (
    id_community           INTEGER     PRIMARY KEY,
    members_see_production BOOLEAN     NOT NULL DEFAULT TRUE,
    members_see_aggregate  BOOLEAN     NOT NULL DEFAULT TRUE,
    -- k-anonymity threshold, counted over n_members and NEVER n_devices: a
    -- member with three meters is one member, and counting devices makes the
    -- guarantee decorative (plan §9.3). Floor 3, default 5.
    k                      SMALLINT    NOT NULL DEFAULT 5,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_community_live_settings_k_floor CHECK (k >= 3)
);

DROP TRIGGER IF EXISTS trg_community_live_settings_updated_at ON community_live_settings;
CREATE TRIGGER trg_community_live_settings_updated_at BEFORE UPDATE ON community_live_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================================
-- INGEST_DEAD_LETTER
--
-- The sole record that a message existed and could not be stored.
--
-- This table is load-bearing in a way it would not be on NATS, and the reason is
-- worth stating where it will be read. aiomqtt 2.x PUBACKs every QoS-1 message
-- the instant paho hands it over — before any database write. (aiomqtt v3 is the
-- only version with a manual `puback()`, and it is alpha and MQTTv5-only, which
-- protocol §1 forbids for devices.) So there is no acknowledgement to withhold,
-- no NACK, and no redelivery counter: the worker gets exactly ONE chance per
-- message, and in-process retry is the only retry there is.
--
-- Deliberately NOT partitioned and deliberately small. If this table grows, the
-- answer is to fix what is failing, not to shard it. What keeps it small is the
-- scheduler's nightly retention: rows older than RETENTION_DEAD_LETTER_DAYS (90)
-- are DELETEd in bounded batches, oldest first, through the received_at index
-- below (worker/retention.py). Without it, a connector that never stops
-- publishing what the worker cannot store grows this table for ever.
-- ============================================================================

CREATE TABLE IF NOT EXISTS ingest_dead_letter (
    id           BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    topic        TEXT        NOT NULL,
    -- NULL when the device could not be identified at all.
    id_device    INTEGER,
    reason       VARCHAR(48) NOT NULL,
    detail       TEXT,
    -- Capped by the caller. A 64 KB payload stored verbatim for every failure
    -- during an outage is its own incident.
    payload      TEXT,
    received_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_ingest_dead_letter_received_at
    ON ingest_dead_letter (received_at DESC);

-- ============================================================================
-- STEP 7/8/9 TABLES  (schema_version 2)
--
-- The ten tables plan §6.1 defers past step 5. They arrive together, in one
-- migration, because they are useless apart: `n_members` needs the ownership
-- projection, the day rollups need the hour rollups, and the forecast tables
-- need somewhere for a method to write.
--
-- EVERY TABLE HERE CARRIES A LITERAL `id_community` COLUMN, including ones where
-- it is derivable. `core/database/with_community.py` hard-codes
-- `model.id_community` behind a `type: ignore`, so a table that names it
-- anything else cannot be scoped at all - and the failure is a runtime 500 in a
-- read path rather than a type error.
--
-- ENERGIES ARE DOUBLE PRECISION, NEVER REAL. `SUM(real)` returns `real`;
-- `measurement` already documents paying that once, and a float4 rollup column
-- would reintroduce the identical unfixable error one level up.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- device_owner_window  (step 7)
--
-- A local projection of CRM ownership, refreshed by the scheduler. It exists so
-- that `n_members` can be resolved AT A BUCKET'S INSTANT without reaching across
-- the database boundary inside the rollup tick.
--
-- `ean` is a plain column and never a foreign key - `meter` lives in crm_db.
--
-- NEVER DENORMALISE THE OWNER ONTO `device`. Ownership is time-sliced: one EAN
-- has several `meter_data` rows and can change holder mid-month. A cached owner
-- is the meter-transfer privacy leak - the previous occupant's credential keeps
-- publishing, attributed to them, about someone else's household.
--
-- `ambiguous` is the row billing does not need. Billing REFUSES a run (422) when
-- it finds overlapping ownership windows; a background projection cannot refuse,
-- so it flags the window instead. An ambiguous window's ENERGY is still counted -
-- excluding it would understate the community total - but its MEMBERSHIP is not,
-- because overcounting members weakens k and undercounting only over-suppresses.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS device_owner_window (
    id            INTEGER     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ean           VARCHAR(64) NOT NULL,
    id_community  INTEGER     NOT NULL,
    -- NULL when the CRM has no owner for this window. The energy still counts;
    -- the member does not.
    id_member     INTEGER,
    -- Brussels-local DATE bounds, mirroring `meter_data.start_date`/`end_date`.
    --
    -- CLOSED AT BOTH ENDS, because meter_data's are. Every existing reader in
    -- the platform tests them as `BETWEEN start_date AND COALESCE(end_date,
    -- 'infinity'::date)` - billing's attribution join and its overlap
    -- pre-flight, and this service's own ports/crm_read.py. Converting to a
    -- half-open form on the way in would mean `valid_to = end_date + 1`, and an
    -- off-by-one there is a whole day of one household's energy attributed to
    -- the wrong member - silently, and only on meters that changed hands, which
    -- is exactly the case this table exists to get right.
    --
    -- So two windows are ADJACENT, not overlapping, when one ends the day before
    -- the next begins: `end_date = next.start_date - 1` is the normal shape of a
    -- transfer and must not be flagged ambiguous. See domain/ownership.py.
    --
    -- `valid_to` NULL means open-ended.
    valid_from    DATE        NOT NULL,
    valid_to      DATE,
    ambiguous     BOOLEAN     NOT NULL DEFAULT FALSE,
    refreshed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Read by the correlated subquery that resolves a device's owner at a bucket.
-- That subquery is correlated rather than a LEFT JOIN precisely because a join
-- fans out on overlapping windows and MULTIPLIES the community energy.
CREATE INDEX IF NOT EXISTS ix_device_owner_window_ean_from
    ON device_owner_window (ean, valid_from DESC);

CREATE INDEX IF NOT EXISTS ix_device_owner_window_community
    ON device_owner_window (id_community);

-- ---------------------------------------------------------------------------
-- rollup_device_hour  (step 8) - PARTITIONED, and registered below.
--
-- plan §6.2: "the maintenance job takes a table list. A job that names only
-- `measurement` lets the rollups freeze about four months in while ingestion
-- goes on looking perfectly healthy."
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rollup_device_hour (
    id_device             INTEGER          NOT NULL,
    -- START of the hour, UTC. Derived from `measurement.ts`, which is the END of
    -- its interval, so a reading at 11:00:00Z lands in bucket 10:00:00Z. See
    -- domain/buckets.py - this one convention is most of step 8's risk.
    bucket                TIMESTAMPTZ      NOT NULL,
    id_community          INTEGER          NOT NULL,
    import_wh             DOUBLE PRECISION NOT NULL,
    export_wh             DOUBLE PRECISION NOT NULL,
    -- NULLABLE, and NEVER coalesced to 0. NULL means "this device does not
    -- measure production" - a P1 on a site that also consumes cannot see it
    -- (protocol §3.4). Writing 0 asserts "produced nothing", a different and
    -- false statement that then propagates into the community total.
    production_wh         DOUBLE PRECISION,
    -- Distinguishes a partial hour (< 4) from a closed one, which is what lets
    -- the hour in progress be published without lying about it.
    n_samples             SMALLINT         NOT NULL,
    n_production_samples  SMALLINT         NOT NULL,
    computed_at           TIMESTAMPTZ      NOT NULL,
    PRIMARY KEY (id_device, bucket)
) PARTITION BY RANGE (bucket);

CREATE TABLE IF NOT EXISTS rollup_device_hour_default
    PARTITION OF rollup_device_hour DEFAULT;

CREATE INDEX IF NOT EXISTS ix_rollup_device_hour_community_bucket
    ON rollup_device_hour (id_community, bucket);

-- ---------------------------------------------------------------------------
-- rollup_device_day  (step 8) - PARTITIONED.
--
-- `bucket` is the instant of LOCAL midnight (Europe/Brussels - see
-- shared/const.ROLLUP_DAY_TIMEZONE). Partitioned even though plan §6.1 names
-- only `_hour`, because §16 requires capping per-device daily retention and
-- partitioning gives the retention job exactly ONE code path, driven by the
-- registry. A second mechanism is a mechanism that gets forgotten.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rollup_device_day (
    id_device             INTEGER          NOT NULL,
    bucket                TIMESTAMPTZ      NOT NULL,
    id_community          INTEGER          NOT NULL,
    import_wh             DOUBLE PRECISION NOT NULL,
    export_wh             DOUBLE PRECISION NOT NULL,
    production_wh         DOUBLE PRECISION,
    -- 23 or 25 on the two DST days, and that is correct rather than a bug.
    n_hours               SMALLINT         NOT NULL,
    n_production_hours    SMALLINT         NOT NULL,
    computed_at           TIMESTAMPTZ      NOT NULL,
    PRIMARY KEY (id_device, bucket)
) PARTITION BY RANGE (bucket);

CREATE TABLE IF NOT EXISTS rollup_device_day_default
    PARTITION OF rollup_device_day DEFAULT;

CREATE INDEX IF NOT EXISTS ix_rollup_device_day_community_bucket
    ON rollup_device_day (id_community, bucket);

-- ---------------------------------------------------------------------------
-- rollup_community_hour / _day  (step 8) - NOT partitioned.
--
-- One row per community per bucket is four orders of magnitude smaller than
-- `measurement`; adding them to the registry would mean two more monthly
-- partitions a month for no operational benefit. §16 treats a community
-- aggregate as non-personal, which is why `_day` has no retention at all.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rollup_community_hour (
    id_community            INTEGER          NOT NULL,
    bucket                  TIMESTAMPTZ      NOT NULL,
    import_wh               DOUBLE PRECISION NOT NULL,
    export_wh               DOUBLE PRECISION NOT NULL,
    production_wh           DOUBLE PRECISION,
    n_devices               SMALLINT         NOT NULL,
    n_devices_production    SMALLINT         NOT NULL,
    -- n_members, NOT n_devices (plan §9.3). "A member with three meters is one
    -- member; counting devices makes the guarantee decorative." Resolved at THIS
    -- BUCKET'S instant, never at now() - resolving at now() would retroactively
    -- rewrite who was in a closed hour.
    n_members               SMALLINT         NOT NULL,
    -- Devices whose owner could not be resolved unambiguously at this bucket.
    -- Their energy is counted; their membership is not. k must threshold on a
    -- LOWER BOUND of distinct members: undercounting over-suppresses,
    -- overcounting is the privacy failure. Fail closed.
    n_devices_unattributed  SMALLINT         NOT NULL,
    computed_at             TIMESTAMPTZ      NOT NULL,
    PRIMARY KEY (id_community, bucket)
);

CREATE TABLE IF NOT EXISTS rollup_community_day (
    id_community            INTEGER          NOT NULL,
    bucket                  TIMESTAMPTZ      NOT NULL,
    import_wh               DOUBLE PRECISION NOT NULL,
    export_wh               DOUBLE PRECISION NOT NULL,
    production_wh           DOUBLE PRECISION,
    n_devices               SMALLINT         NOT NULL,
    n_devices_production    SMALLINT         NOT NULL,
    -- MAX over the day's hours, NEVER SUM. SUM gives a 5-member community an
    -- n_members of 120 and k then passes on a day that should be suppressed.
    -- MAX is a valid lower bound on the day's distinct union, so it fails closed.
    n_members               SMALLINT         NOT NULL,
    n_devices_unattributed  SMALLINT         NOT NULL,
    n_hours                 SMALLINT         NOT NULL,
    computed_at             TIMESTAMPTZ      NOT NULL,
    PRIMARY KEY (id_community, bucket)
);

-- ---------------------------------------------------------------------------
-- rollup_dirty  (step 8)
--
-- Buckets awaiting recompute. Granularity is COMMUNITY-hour rather than
-- device-hour because the unit of recomputation is the community hour:
-- `n_members` cannot be computed for one device. Device granularity would
-- produce four times the rows and the sweep would collapse them anyway.
--
-- Written in the SAME STATEMENT as the measurement, unconditionally, with no
-- guard band - see worker/ingest.py. Marking only "outside the window" loses a
-- bucket written at 10:59:59 when the tick fires at 11:00:02, and loses
-- everything ingested during a scheduler outage.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rollup_dirty (
    id_community  INTEGER     NOT NULL,
    bucket        TIMESTAMPTZ NOT NULL,
    marked_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_community, bucket)
);

-- Not decoration. This is a delete/insert queue on the ingest hot path: a
-- 50-device community makes 50 speculative inserts per quarter-hour against one
-- key, 49 of which conflict. At the default scale factor the "tiny table"
-- becomes a bloated one and the PK prefix scan the drain depends on stops being
-- cheap.
ALTER TABLE rollup_dirty SET (autovacuum_vacuum_scale_factor = 0.0,
                              autovacuum_vacuum_threshold   = 50);

-- ---------------------------------------------------------------------------
-- forecast_production / device_forecast_method  (step 9) - INERT.
--
-- Created now so the contract is fixed before any method exists; nothing writes
-- them in phase 1. `method` and `method_version` are NOT optional (plan §10.3):
-- without them two methods cannot be compared, a retro-adjustment cannot be
-- attributed, and rows produced by a model since corrected cannot be found.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS forecast_production (
    ean             VARCHAR(64)      NOT NULL,
    bucket          TIMESTAMPTZ      NOT NULL,
    id_community    INTEGER          NOT NULL,
    wh              DOUBLE PRECISION NOT NULL,
    method          VARCHAR(64)      NOT NULL,
    method_version  VARCHAR(32)      NOT NULL,
    computed_at     TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ean, bucket, method)
);

CREATE INDEX IF NOT EXISTS ix_forecast_production_community_bucket
    ON forecast_production (id_community, bucket);

CREATE TABLE IF NOT EXISTS device_forecast_method (
    id_device   INTEGER     PRIMARY KEY REFERENCES device (id) ON DELETE CASCADE,
    method      VARCHAR(64) NOT NULL,
    params      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- OR REPLACE, not a bare CREATE: PostgreSQL has no CREATE TRIGGER IF NOT
-- EXISTS, so a bare one makes this file non-re-runnable - which the conftest
-- fixture, applying schema.sql and then every migration on top of it, catches
-- on every test run. Available since PG 14; the stack pins postgres:18.
CREATE OR REPLACE TRIGGER trg_device_forecast_method_updated_at
    BEFORE UPDATE ON device_forecast_method
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- consent / consent_event  (phase 2) - INERT.
--
-- Append-only with PER-FIELD `effective_from`, which is the only shape that
-- satisfies §9's per-field, per-direction retroactivity: a withdrawal applies to
-- the past by default, an addition does not. Read with
-- `DISTINCT ON (id_member, field) ... ORDER BY decided_at DESC, id DESC`.
--
-- Visibility is evaluated AT READ TIME, never at write time. Measurements are
-- always stored; a withdrawal masks them.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consent (
    id              INTEGER     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_community    INTEGER     NOT NULL,
    id_member       INTEGER     NOT NULL,
    -- admin_can_view_individual | share_with_community | show_on_map
    field           VARCHAR(48) NOT NULL,
    granted         BOOLEAN     NOT NULL,
    -- NULL means "from the beginning of time" - a withdrawal applying to the
    -- past. An addition carries the instant it was decided.
    effective_from  TIMESTAMPTZ,
    decided_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_consent_member_field
    ON consent (id_member, field, decided_at DESC);

CREATE INDEX IF NOT EXISTS ix_consent_community
    ON consent (id_community);

CREATE TABLE IF NOT EXISTS consent_event (
    id            INTEGER     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_consent    INTEGER     NOT NULL REFERENCES consent (id) ON DELETE CASCADE,
    id_community  INTEGER     NOT NULL,
    actor         VARCHAR(64) NOT NULL,
    action        VARCHAR(32) NOT NULL,
    recorded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_consent_event_consent
    ON consent_event (id_consent);

-- ---------------------------------------------------------------------------
-- The partition registry gains the two partitioned rollups.
--
-- domain/partitions.PARTITIONED_TABLES carries the same list, and
-- tests/test_partitions.py asserts the two agree. That test is what stops the
-- failure plan §6.2 names by name.
-- ---------------------------------------------------------------------------
INSERT INTO live_partitioned_table (table_name) VALUES
    ('rollup_device_hour'),
    ('rollup_device_day')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- live_ensure_monthly_partitions gains `months_back`.
--
-- The old signature only ever provisioned forward from the current month, so
-- nothing re-created a PAST month. With `INGEST_MAX_AGE_DAYS = 35` a legitimate
-- late message reaches two calendar months back; on a freshly provisioned or
-- restored database those partitions do not exist, the message lands in the
-- DEFAULT partition, and `/health/readiness` goes red on day one looking exactly
-- like an ingest bug.
--
-- DROP THEN CREATE, not CREATE OR REPLACE. Adding a parameter to a plpgsql
-- function creates a second OVERLOAD rather than replacing it, and a later
-- `live_ensure_monthly_partitions(6)` call then resolves ambiguously.
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS live_ensure_monthly_partitions(INTEGER);

CREATE OR REPLACE FUNCTION live_ensure_monthly_partitions(
    months_ahead INTEGER DEFAULT 6,
    months_back  INTEGER DEFAULT 2
)
RETURNS INTEGER AS $$
DECLARE
  tbl          RECORD;
  offset_m     INTEGER;
  lower_bound  TIMESTAMPTZ;
  upper_bound  TIMESTAMPTZ;
  child        TEXT;
  created      INTEGER := 0;
BEGIN
  FOR tbl IN SELECT table_name FROM live_partitioned_table LOOP
    FOR offset_m IN -months_back..months_ahead LOOP
      -- Anchored to UTC EXPLICITLY. date_trunc() on a timestamptz truncates in
      -- the SESSION's timezone, and provision.sh sets none - so without the
      -- round trip through UTC a boundary would land at 23:00 or 01:00 of the
      -- previous day whenever the session happened to be Europe/Brussels, and
      -- every partition in the database would be an hour wide of the Python
      -- helper that names it.
      lower_bound := (date_trunc('month', (now() AT TIME ZONE 'UTC'))
                      + make_interval(months => offset_m)) AT TIME ZONE 'UTC';
      upper_bound := (date_trunc('month', (now() AT TIME ZONE 'UTC'))
                      + make_interval(months => offset_m + 1)) AT TIME ZONE 'UTC';
      child := format('%s_%s', tbl.table_name, to_char(lower_bound AT TIME ZONE 'UTC', 'YYYY_MM'));

      -- IF NOT EXISTS makes the whole function idempotent, which is what lets it
      -- be called both from schema.sql and from a daily tick.
      --
      -- NOTE it can still FAIL, and that is not a bug in this function: creating
      -- a partition over a range the DEFAULT partition already holds rows in
      -- requires a scan proving the default is empty there. worker/partitions.py
      -- drains the default first. Without that drain this call starts failing
      -- about three months after launch, at 00:00 UTC on the 1st.
      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
        child, tbl.table_name, lower_bound, upper_bound
      );
      created := created + 1;
    END LOOP;
  END LOOP;
  RETURN created;
END;
$$ LANGUAGE plpgsql;

-- Provision two months back, the current month, and six ahead, for every table
-- now in the registry.
SELECT live_ensure_monthly_partitions(6, 2);

INSERT INTO schema_version (version, description) VALUES
    (2, 'Rollups, ownership projection, forecast and consent tables (steps 7-9)')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- MIGRATION 0002 - device.production_chain  (build step 9)
--
-- RE-RUNNABLE, like everything in this directory. `ADD COLUMN IF NOT EXISTS`
-- rather than a bare ADD: tests/conftest.py applies schema.sql and then every
-- migration on top of it, which is what proves each one can be applied twice.
--
-- shared.const.ProductionChain, mirroring crm-backend's enum:
--   1 PHOTOVOLTAIC, 2 WIND, 3 HYDRO, 4 BIOMASS, 5 BIOGAS, 6 COGEN_FOSSIL, 7 OTHER.
--
-- NULLABLE, and null is a real answer rather than a default: `meter_data`
-- carries no chain for a meter nobody classified, and the registry treats an
-- unknown chain as matching NO method. Defaulting it to PHOTOVOLTAIC because
-- that is the common case would silently forecast a hydro installation with a
-- solar model - the one failure this column exists to make impossible.
--
-- A SNAPSHOT, taken at device creation alongside capacity_kva, for the reason
-- that column states: the forecast job runs per device in the worker, and a CRM
-- round trip per device per run is the cost this service already declined.
-- ============================================================================

ALTER TABLE device ADD COLUMN IF NOT EXISTS production_chain SMALLINT;

INSERT INTO schema_version (version, description)
VALUES (3, 'device.production_chain for the forecast seam (build step 9)')
ON CONFLICT (version) DO NOTHING;

-- ============================================================================
-- MIGRATION 0003 - sharing operations  (decision D-14, 2026-10-04)
--
-- RE-RUNNABLE, like everything in this directory.
--
-- What it adds:
--   * device_owner_window.id_sharing_operation - the CRM window's operation,
--     projected with the member by worker/ownership.py.
--   * rollup_operation_hour / _day - one row per (community, operation, bucket)
--     with the operation's import, export, production and the ESTIMATED energy
--     shared inside it, plus one REMAINDER row per bucket (id 0) for every
--     device that belongs to no operation at that bucket.
--   * rollup_community_day.n_members_min - the day's LEAST-populated hour.
--
-- ---------------------------------------------------------------------------
-- THE REMAINDER ROW (id_sharing_operation = 0) IS A PRIVACY DEVICE.
--
-- Devices in no operation (none in the CRM, an ambiguous window, no window, a
-- meter still WAITING_GRD) go to row 0. Every device-hour then lands in exactly
-- one row, so the rows of a bucket sum to the community total EXACTLY. The
-- global view is published only when subtracting the visible operations from it
-- cannot expose fewer than k members (domain/kanon.py), and that test needs to
-- know whether anything outside the visible operations exists at all. Counting
-- devices cannot tell: a day's MAX device counts do not add up across rows.
-- A row can. CRM ids are identity columns from 1, so 0 is free.
--
-- shared_wh is NULL exactly on row 0 (nothing is shared outside an operation)
-- and never NULL elsewhere: the CHECK makes both halves structural.
--
-- ---------------------------------------------------------------------------
-- shared_wh IS AN ESTIMATE, AND NOT AN UPPER BOUND.
--
-- Per quarter-hour, LEAST(sum of export, sum of import) over the operation's
-- MONITORED meters, summed into the hour. Never computed from hourly sums: a
-- noon surplus cannot cover an evening offtake, and the hourly form says it
-- can. The DSO's figure may be lower (its allocation key may share less) or
-- higher (consumption at meters with no device). The DSO's data stays the only
-- basis for allocation keys and invoicing.
--
-- ---------------------------------------------------------------------------
-- PARTITIONED, KEPT 13 MONTHS. An operation of two households is two
-- households: unlike the community aggregate, these rows are personal data, so
-- they get the device rollups' retention and its one code path (the registry).
--
-- Their partitions MIRROR the device rollups' existing ones (the DO block):
-- every operation row is derived from a device-hour row, so a month that holds
-- device rollups needs an operation partition too - or the first backfill lands
-- history in *_default and /health/readiness goes red. live_ensure_monthly_
-- partitions alone would only cover two months back.
-- ============================================================================

ALTER TABLE device_owner_window ADD COLUMN IF NOT EXISTS id_sharing_operation INTEGER;

ALTER TABLE rollup_community_day ADD COLUMN IF NOT EXISTS n_members_min SMALLINT;

CREATE TABLE IF NOT EXISTS rollup_operation_hour (
    id_community            INTEGER          NOT NULL,
    -- 0 = the remainder: devices in no operation at this bucket.
    id_sharing_operation    INTEGER          NOT NULL,
    bucket                  TIMESTAMPTZ      NOT NULL,
    import_wh               DOUBLE PRECISION NOT NULL,
    export_wh               DOUBLE PRECISION NOT NULL,
    production_wh           DOUBLE PRECISION,
    shared_wh               DOUBLE PRECISION,
    n_devices               SMALLINT         NOT NULL,
    n_devices_production    SMALLINT         NOT NULL,
    -- Distinct members whose window put a device here, at this bucket's date.
    -- A lower bound, like the community's: an unattributed device adds energy
    -- and no member, so k fails closed.
    n_members               SMALLINT         NOT NULL,
    computed_at             TIMESTAMPTZ      NOT NULL,
    PRIMARY KEY (id_community, id_sharing_operation, bucket),
    CONSTRAINT ck_rollup_operation_hour_operation CHECK (id_sharing_operation >= 0),
    CONSTRAINT ck_rollup_operation_hour_shared
        CHECK ((id_sharing_operation = 0) = (shared_wh IS NULL))
) PARTITION BY RANGE (bucket);

CREATE TABLE IF NOT EXISTS rollup_operation_hour_default
    PARTITION OF rollup_operation_hour DEFAULT;

CREATE TABLE IF NOT EXISTS rollup_operation_day (
    id_community            INTEGER          NOT NULL,
    id_sharing_operation    INTEGER          NOT NULL,
    -- LOCAL midnight (Europe/Brussels), like every day bucket here.
    bucket                  TIMESTAMPTZ      NOT NULL,
    import_wh               DOUBLE PRECISION NOT NULL,
    export_wh               DOUBLE PRECISION NOT NULL,
    production_wh           DOUBLE PRECISION,
    shared_wh               DOUBLE PRECISION,
    n_devices               SMALLINT         NOT NULL,
    n_devices_production    SMALLINT         NOT NULL,
    -- MAX over the day's hours, as for the community: a lower bound on the day.
    n_members               SMALLINT         NOT NULL,
    -- MIN over the day's hours. A day is published only if EVERY hour of it
    -- was: otherwise "day minus its published hours" is the withheld hours.
    n_members_min           SMALLINT         NOT NULL,
    n_hours                 SMALLINT         NOT NULL,
    computed_at             TIMESTAMPTZ      NOT NULL,
    PRIMARY KEY (id_community, id_sharing_operation, bucket),
    CONSTRAINT ck_rollup_operation_day_operation CHECK (id_sharing_operation >= 0),
    CONSTRAINT ck_rollup_operation_day_shared
        CHECK ((id_sharing_operation = 0) = (shared_wh IS NULL))
) PARTITION BY RANGE (bucket);

CREATE TABLE IF NOT EXISTS rollup_operation_day_default
    PARTITION OF rollup_operation_day DEFAULT;

INSERT INTO live_partitioned_table (table_name) VALUES
    ('rollup_operation_hour'),
    ('rollup_operation_day')
ON CONFLICT DO NOTHING;

-- Mirror every monthly partition the device rollups already have, then the
-- usual window. Names and bounds follow live_ensure_monthly_partitions exactly
-- (`<table>_YYYY_MM`, UTC month bounds), so the two never disagree.
DO $$
DECLARE
  pair         TEXT[];
  suffix       TEXT;
  lower_bound  TIMESTAMPTZ;
  upper_bound  TIMESTAMPTZ;
BEGIN
  FOREACH pair SLICE 1 IN ARRAY ARRAY[
      ARRAY['rollup_device_hour', 'rollup_operation_hour'],
      ARRAY['rollup_device_day',  'rollup_operation_day']
  ] LOOP
    FOR suffix IN
      SELECT right(c.relname, 7)
        FROM pg_inherits i
        JOIN pg_class c ON c.oid = i.inhrelid
       WHERE i.inhparent = pair[1]::regclass
         AND c.relname ~ '_[0-9]{4}_[0-9]{2}$'
    LOOP
      lower_bound := (to_date(suffix, 'YYYY_MM')::timestamp) AT TIME ZONE 'UTC';
      upper_bound := ((to_date(suffix, 'YYYY_MM') + INTERVAL '1 month')::timestamp)
                     AT TIME ZONE 'UTC';
      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
        pair[2] || '_' || suffix, pair[2], lower_bound, upper_bound
      );
    END LOOP;
  END LOOP;
END $$;

SELECT live_ensure_monthly_partitions(6, 2);

INSERT INTO schema_version (version, description)
VALUES (4, 'Sharing operations: owner-window operation, operation rollups (D-14)')
ON CONFLICT (version) DO NOTHING;
